remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Bot开发者中心(测试版)
lang: en
description: Bot开发文档

readme_index:
  with_frontmatter: true

github_edit_link: false

github_docs_folder: false

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
