remote_theme: rundocs/jekyll-rtd-theme

title: upbot开发者中心(测试版)
lang: en
description: upbot开发文档

readme_index:
  with_frontmatter: true

github_edit_link: false

github_docs_folder: false

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
